[2025-08-07T00:00:01.506+0000] {processor.py:161} INFO - Started process (PID=7730) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:00:01.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:00:01.511+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:00:01.511+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:00:01.519+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:00:01.518+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:00:01.519+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:00:01.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.054 seconds
[2025-08-07T00:00:31.988+0000] {processor.py:161} INFO - Started process (PID=7745) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:00:31.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:00:31.997+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:00:31.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:00:32.003+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:00:32.002+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:00:32.003+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:00:32.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.056 seconds
[2025-08-07T00:01:02.486+0000] {processor.py:161} INFO - Started process (PID=7760) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:02.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:01:02.496+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:01:02.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:02.503+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:01:02.501+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:01:02.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:02.536+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.063 seconds
[2025-08-07T00:01:33.024+0000] {processor.py:161} INFO - Started process (PID=7775) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:33.026+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:01:33.030+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:01:33.030+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:33.035+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:01:33.034+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:01:33.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:33.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.063 seconds
[2025-08-07T00:01:39.296+0000] {processor.py:161} INFO - Started process (PID=7790) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:39.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:01:39.298+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:01:39.298+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:39.302+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:01:39.301+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:01:39.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:39.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.027 seconds
[2025-08-07T00:01:40.318+0000] {processor.py:161} INFO - Started process (PID=7795) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:40.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:01:40.321+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:01:40.320+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:40.324+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:01:40.323+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:01:40.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:01:40.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.030 seconds
[2025-08-07T00:02:10.957+0000] {processor.py:161} INFO - Started process (PID=7810) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:02:10.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:02:10.961+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:02:10.961+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:02:10.964+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:02:10.964+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:02:10.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:02:10.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.037 seconds
[2025-08-07T00:02:41.519+0000] {processor.py:161} INFO - Started process (PID=7825) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:02:41.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:02:41.526+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:02:41.526+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:02:41.530+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:02:41.529+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:02:41.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:02:41.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.036 seconds
[2025-08-07T00:03:12.071+0000] {processor.py:161} INFO - Started process (PID=7840) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:03:12.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:03:12.076+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:03:12.075+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:03:12.081+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:03:12.079+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:03:12.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:03:12.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.034 seconds
[2025-08-07T00:03:42.567+0000] {processor.py:161} INFO - Started process (PID=7855) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:03:42.569+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:03:42.571+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:03:42.571+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:03:42.576+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:03:42.574+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:03:42.576+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:03:42.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.031 seconds
[2025-08-07T00:04:13.150+0000] {processor.py:161} INFO - Started process (PID=7870) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:04:13.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:04:13.155+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:04:13.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:04:13.158+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:04:13.157+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:04:13.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:04:13.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.029 seconds
[2025-08-07T00:04:43.734+0000] {processor.py:161} INFO - Started process (PID=7885) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:04:43.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:04:43.744+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:04:43.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:04:43.750+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:04:43.749+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:04:43.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:04:43.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.060 seconds
[2025-08-07T00:05:14.322+0000] {processor.py:161} INFO - Started process (PID=7900) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:05:14.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:05:14.326+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:05:14.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:05:14.330+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:05:14.329+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:05:14.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:05:14.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.030 seconds
[2025-08-07T00:05:44.840+0000] {processor.py:161} INFO - Started process (PID=7915) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:05:44.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:05:44.843+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:05:44.843+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:05:44.846+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:05:44.845+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:05:44.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:05:44.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.026 seconds
[2025-08-07T00:06:15.361+0000] {processor.py:161} INFO - Started process (PID=7930) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:06:15.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:06:15.364+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:06:15.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:06:15.367+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:06:15.366+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:06:15.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:06:15.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.022 seconds
[2025-08-07T00:06:45.939+0000] {processor.py:161} INFO - Started process (PID=7945) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:06:45.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:06:45.943+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:06:45.942+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:06:45.946+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:06:45.945+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:06:45.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:06:45.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.032 seconds
[2025-08-07T00:07:16.467+0000] {processor.py:161} INFO - Started process (PID=7960) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:07:16.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:07:16.472+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:16.472+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:07:16.476+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:16.475+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/load/s3_to_snowflake_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load/s3_to_snowflake_loader.py", line 31
    AWS_KEY_ID= '{aws_creds.access_key}',
                ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: expecting '!', or ':', or '}'
[2025-08-07T00:07:16.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:07:16.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.033 seconds
[2025-08-07T00:07:27.757+0000] {processor.py:161} INFO - Started process (PID=7965) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:07:27.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:07:27.761+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.760+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:07:27.789+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.789+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:07:27.804+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.804+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:07:27.805+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.805+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:07:27.816+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.815+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:07:27.816+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.816+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:07:27.816+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.816+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:07:27.830+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:07:27.971+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.970+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:s3_to_snowflake_loader
[2025-08-07T00:07:27.975+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.975+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:s3_to_snowflake_loader
[2025-08-07T00:07:27.977+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.976+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:s3_to_snowflake_loader
[2025-08-07T00:07:27.977+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.977+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:07:27.985+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.985+0000] {dag.py:3118} INFO - Creating ORM DAG for s3_to_snowflake_loader
[2025-08-07T00:07:27.985+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:27.985+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:07:27.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.251 seconds
[2025-08-07T00:07:58.338+0000] {processor.py:161} INFO - Started process (PID=7980) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:07:58.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:07:58.343+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:58.343+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:07:58.383+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:58.382+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:07:58.399+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:58.399+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:07:58.401+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:58.401+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:07:58.410+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:58.410+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:07:58.411+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:58.411+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:07:58.411+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:58.411+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:07:58.429+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:07:58.450+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:58.450+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:07:58.460+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:07:58.460+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:07:58.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.143 seconds
[2025-08-07T00:08:28.990+0000] {processor.py:161} INFO - Started process (PID=7995) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:08:28.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:08:28.997+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:28.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:08:29.030+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:29.030+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:08:29.046+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:29.045+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:08:29.047+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:29.047+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:08:29.052+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:29.052+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:08:29.052+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:29.052+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:08:29.053+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:29.052+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:08:29.074+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:08:29.084+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:29.084+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:08:29.093+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:29.093+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:08:29.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.133 seconds
[2025-08-07T00:08:59.664+0000] {processor.py:161} INFO - Started process (PID=8010) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:08:59.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:08:59.669+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:59.669+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:08:59.703+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:59.703+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:08:59.721+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:59.720+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:08:59.722+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:59.722+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:08:59.727+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:59.727+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:08:59.727+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:59.727+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:08:59.728+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:59.728+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:08:59.746+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:08:59.757+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:59.757+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:08:59.769+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:08:59.769+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:08:59.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.124 seconds
[2025-08-07T00:09:30.185+0000] {processor.py:161} INFO - Started process (PID=8045) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:09:30.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:09:30.191+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:09:30.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:09:30.220+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:09:30.220+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:09:30.234+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:09:30.234+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:09:30.235+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:09:30.235+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:09:30.242+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:09:30.242+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:09:30.243+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:09:30.243+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:09:30.243+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:09:30.243+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:09:30.260+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:09:30.273+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:09:30.273+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:09:30.282+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:09:30.282+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:09:30.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.123 seconds
[2025-08-07T00:10:00.752+0000] {processor.py:161} INFO - Started process (PID=8060) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:10:00.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:10:00.758+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:00.757+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:10:00.790+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:00.790+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:10:00.807+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:00.807+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:10:00.809+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:00.809+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:10:00.813+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:00.813+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:10:00.813+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:00.813+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:10:00.814+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:00.813+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:10:00.831+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:10:00.842+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:00.842+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:10:00.851+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:00.851+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:10:00.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.120 seconds
[2025-08-07T00:10:31.174+0000] {processor.py:161} INFO - Started process (PID=8075) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:10:31.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:10:31.180+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:31.179+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:10:31.213+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:31.212+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:10:31.226+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:31.226+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:10:31.228+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:31.228+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:10:31.232+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:31.232+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:10:31.233+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:31.233+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:10:31.233+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:31.233+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:10:31.250+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:10:31.261+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:31.261+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:10:31.269+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:10:31.269+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:10:31.278+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.109 seconds
[2025-08-07T00:11:01.714+0000] {processor.py:161} INFO - Started process (PID=8090) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:11:01.715+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:11:01.717+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:01.717+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:11:01.734+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:01.734+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:11:01.743+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:01.743+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:11:01.744+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:01.744+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:11:01.747+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:01.747+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:11:01.748+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:01.748+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:11:01.748+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:01.748+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:11:01.760+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:11:01.771+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:01.771+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:11:01.784+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:01.784+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:11:01.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.088 seconds
[2025-08-07T00:11:32.210+0000] {processor.py:161} INFO - Started process (PID=8105) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:11:32.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:11:32.215+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:32.214+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:11:32.250+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:32.250+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:11:32.265+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:32.264+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:11:32.266+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:32.266+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:11:32.273+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:32.273+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:11:32.274+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:32.274+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:11:32.274+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:32.274+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:11:32.294+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:11:32.308+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:32.308+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:11:32.318+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:11:32.318+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:11:32.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.128 seconds
[2025-08-07T00:12:02.770+0000] {processor.py:161} INFO - Started process (PID=8120) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:12:02.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:12:02.775+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:02.774+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:12:02.809+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:02.809+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:12:02.829+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:02.829+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:12:02.830+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:02.830+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:12:02.836+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:02.836+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:12:02.837+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:02.837+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:12:02.837+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:02.837+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:12:02.854+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:12:02.864+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:02.864+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:12:02.872+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:02.872+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:12:02.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.129 seconds
[2025-08-07T00:12:33.232+0000] {processor.py:161} INFO - Started process (PID=8135) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:12:33.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:12:33.237+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:33.236+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:12:33.253+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:33.253+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:12:33.260+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:33.260+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:12:33.261+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:33.260+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:12:33.264+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:33.264+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:12:33.264+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:33.264+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:12:33.265+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:33.265+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:12:33.277+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:12:33.285+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:33.284+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:12:33.296+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:12:33.296+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:12:33.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.084 seconds
[2025-08-07T00:13:03.737+0000] {processor.py:161} INFO - Started process (PID=8150) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:13:03.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:13:03.742+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:03.742+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:13:03.779+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:03.779+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:13:03.795+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:03.795+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:13:03.797+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:03.796+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:13:03.802+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:03.802+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:13:03.803+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:03.803+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:13:03.803+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:03.803+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:13:03.824+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:13:03.836+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:03.835+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:13:03.846+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:03.846+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:13:03.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.130 seconds
[2025-08-07T00:13:34.310+0000] {processor.py:161} INFO - Started process (PID=8165) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:13:34.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:13:34.315+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:34.315+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:13:34.347+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:34.347+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:13:34.364+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:34.364+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:13:34.365+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:34.365+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:13:34.370+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:34.370+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:13:34.371+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:34.370+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:13:34.371+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:34.371+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:13:34.390+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:13:34.402+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:34.402+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:13:34.411+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:13:34.410+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:13:34.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.124 seconds
[2025-08-07T00:14:04.904+0000] {processor.py:161} INFO - Started process (PID=8180) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:14:04.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:14:04.913+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:04.912+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:14:04.954+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:04.954+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:14:04.971+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:04.970+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:14:04.972+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:04.971+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:14:04.976+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:04.976+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:14:04.977+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:04.976+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:14:04.977+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:04.977+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:14:04.999+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:14:05.014+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:05.014+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:14:05.023+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:05.023+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:14:05.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.144 seconds
[2025-08-07T00:14:35.658+0000] {processor.py:161} INFO - Started process (PID=8195) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:14:35.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:14:35.678+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:35.677+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:14:35.741+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:35.740+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:14:36.118+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:36.116+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:14:36.138+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:36.133+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:14:36.163+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:36.163+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:14:36.164+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:36.164+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:14:36.165+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:36.164+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:14:36.208+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:14:36.233+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:36.233+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:14:36.250+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:14:36.250+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:14:36.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.634 seconds
[2025-08-07T00:15:06.832+0000] {processor.py:161} INFO - Started process (PID=8210) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:15:06.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:15:06.839+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:06.839+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:15:06.887+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:06.887+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:15:06.905+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:06.905+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:15:06.906+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:06.906+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:15:06.910+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:06.910+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:15:06.911+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:06.911+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:15:06.911+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:06.911+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:15:06.933+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:15:06.944+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:06.944+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:15:06.957+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:06.957+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:15:06.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.152 seconds
[2025-08-07T00:15:37.443+0000] {processor.py:161} INFO - Started process (PID=8225) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:15:37.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:15:37.449+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:37.448+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:15:37.485+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:37.485+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:15:37.501+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:37.501+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:15:37.503+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:37.503+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:15:37.511+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:37.510+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:15:37.511+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:37.511+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:15:37.511+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:37.511+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:15:37.528+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:15:37.542+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:37.542+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:15:37.553+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:15:37.553+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:15:37.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.136 seconds
[2025-08-07T00:16:07.892+0000] {processor.py:161} INFO - Started process (PID=8240) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:16:07.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:16:07.896+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:07.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:16:07.923+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:07.923+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:16:07.932+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:07.932+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:16:07.933+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:07.933+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:16:07.937+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:07.937+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:16:07.937+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:07.937+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:16:07.937+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:07.937+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:16:07.950+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:16:07.957+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:07.957+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:16:07.966+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:07.966+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:16:07.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.096 seconds
[2025-08-07T00:16:38.355+0000] {processor.py:161} INFO - Started process (PID=8255) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:16:38.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:16:38.361+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:38.360+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:16:38.395+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:38.395+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:16:38.410+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:38.410+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:16:38.412+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:38.411+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:16:38.418+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:38.418+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:16:38.419+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:38.418+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:16:38.419+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:38.419+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:16:38.440+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:16:38.453+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:38.453+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:16:38.464+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:16:38.464+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:16:38.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.131 seconds
[2025-08-07T00:17:08.896+0000] {processor.py:161} INFO - Started process (PID=8270) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:17:08.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:17:08.902+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:08.901+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:17:08.933+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:08.933+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:17:08.950+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:08.950+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:17:08.951+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:08.951+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:17:08.957+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:08.957+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:17:08.957+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:08.957+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:17:08.957+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:08.957+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:17:08.976+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:17:08.987+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:08.987+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:17:08.999+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:08.999+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:17:09.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.130 seconds
[2025-08-07T00:17:39.389+0000] {processor.py:161} INFO - Started process (PID=8285) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:17:39.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:17:39.394+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:39.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:17:39.416+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:39.416+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:17:39.425+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:39.425+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:17:39.426+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:39.426+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:17:39.430+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:39.430+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:17:39.430+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:39.430+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:17:39.430+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:39.430+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:17:39.443+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:17:39.451+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:39.451+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:17:39.460+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:17:39.460+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:17:39.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.089 seconds
[2025-08-07T00:18:09.911+0000] {processor.py:161} INFO - Started process (PID=8300) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:18:09.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:18:09.917+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:09.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:18:09.944+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:09.944+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:18:09.951+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:09.951+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:18:09.952+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:09.952+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:18:09.956+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:09.956+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:18:09.956+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:09.956+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:18:09.957+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:09.957+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:18:09.969+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:18:09.977+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:09.977+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:18:09.985+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:09.985+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:18:09.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.093 seconds
[2025-08-07T00:18:40.486+0000] {processor.py:161} INFO - Started process (PID=8315) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:18:40.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:18:40.499+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:40.498+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:18:40.555+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:40.555+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:18:40.578+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:40.578+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:18:40.580+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:40.579+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:18:40.585+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:40.585+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:18:40.586+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:40.586+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:18:40.586+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:40.586+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:18:40.609+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:18:40.622+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:40.621+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:18:40.631+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:18:40.631+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:18:40.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.183 seconds
[2025-08-07T00:19:11.133+0000] {processor.py:161} INFO - Started process (PID=8330) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:19:11.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:19:11.144+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:11.143+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:19:11.188+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:11.188+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:19:11.209+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:11.209+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:19:11.211+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:11.211+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:19:11.216+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:11.216+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:19:11.217+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:11.217+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:19:11.217+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:11.217+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:19:11.238+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:19:11.250+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:11.250+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:19:11.264+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:11.264+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:19:11.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.174 seconds
[2025-08-07T00:19:41.804+0000] {processor.py:161} INFO - Started process (PID=8345) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:19:41.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:19:41.814+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:41.814+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:19:41.860+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:41.860+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:19:41.878+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:41.878+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:19:41.879+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:41.879+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:19:41.886+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:41.886+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:19:41.886+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:41.886+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:19:41.887+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:41.887+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:19:41.906+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:19:41.921+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:41.921+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:19:41.935+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:19:41.935+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:19:41.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.159 seconds
[2025-08-07T00:20:12.410+0000] {processor.py:161} INFO - Started process (PID=8360) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:20:12.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:20:12.420+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:12.419+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:20:12.450+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:12.450+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:20:12.466+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:12.466+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:20:12.467+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:12.467+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:20:12.471+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:12.471+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:20:12.471+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:12.471+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:20:12.471+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:12.471+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:20:12.491+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:20:12.501+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:12.500+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:20:12.513+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:12.513+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:20:12.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.124 seconds
[2025-08-07T00:20:42.971+0000] {processor.py:161} INFO - Started process (PID=8375) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:20:42.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:20:42.978+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:42.978+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:20:43.015+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:43.014+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:20:43.035+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:43.034+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:20:43.036+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:43.035+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:20:43.040+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:43.040+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:20:43.041+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:43.041+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:20:43.041+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:43.041+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:20:43.062+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:20:43.075+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:43.075+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:20:43.084+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:20:43.084+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:20:43.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.142 seconds
[2025-08-07T00:21:13.435+0000] {processor.py:161} INFO - Started process (PID=8390) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:21:13.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:21:13.440+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:13.440+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:21:13.463+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:13.463+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:21:13.471+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:13.471+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:21:13.473+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:13.473+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:21:13.476+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:13.476+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:21:13.477+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:13.476+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:21:13.477+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:13.477+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:21:13.489+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:21:13.498+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:13.497+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:21:13.510+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:13.510+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:21:13.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.096 seconds
[2025-08-07T00:21:43.919+0000] {processor.py:161} INFO - Started process (PID=8405) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:21:43.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:21:43.924+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:43.923+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:21:43.956+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:43.956+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:21:43.972+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:43.972+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:21:43.974+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:43.974+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:21:43.980+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:43.979+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:21:43.980+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:43.980+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:21:43.980+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:43.980+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:21:43.996+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:21:44.010+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:44.010+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:21:44.020+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:21:44.020+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:21:44.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.124 seconds
[2025-08-07T00:22:14.389+0000] {processor.py:161} INFO - Started process (PID=8420) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:22:14.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:22:14.393+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:14.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:22:14.418+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:14.418+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:22:14.429+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:14.429+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:22:14.430+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:14.430+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:22:14.434+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:14.434+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:22:14.434+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:14.434+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:22:14.434+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:14.434+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:22:14.446+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:22:14.455+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:14.455+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:22:14.463+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:14.463+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:22:14.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.096 seconds
[2025-08-07T00:22:44.849+0000] {processor.py:161} INFO - Started process (PID=8435) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:22:44.850+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:22:44.854+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:44.853+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:22:44.882+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:44.882+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:22:44.899+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:44.899+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:22:44.901+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:44.900+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:22:44.905+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:44.905+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:22:44.906+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:44.906+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:22:44.906+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:44.906+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:22:44.922+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:22:44.933+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:44.933+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:22:44.944+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:22:44.944+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:22:44.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.116 seconds
[2025-08-07T00:23:15.407+0000] {processor.py:161} INFO - Started process (PID=8450) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:23:15.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:23:15.416+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:15.416+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:23:15.452+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:15.452+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:23:15.470+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:15.469+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:23:15.471+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:15.470+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:23:15.479+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:15.479+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:23:15.479+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:15.479+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:23:15.480+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:15.480+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:23:15.497+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:23:15.511+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:15.511+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:23:15.520+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:15.520+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:23:15.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.133 seconds
[2025-08-07T00:23:46.033+0000] {processor.py:161} INFO - Started process (PID=8465) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:23:46.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:23:46.043+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:46.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:23:46.085+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:46.084+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:23:47.107+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:47.107+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:23:47.135+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:47.135+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:23:47.143+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:47.143+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:23:47.143+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:47.143+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:23:47.143+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:47.143+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:23:47.166+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:23:47.180+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:47.180+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:23:47.190+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:23:47.190+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:23:47.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 1.179 seconds
[2025-08-07T00:24:17.742+0000] {processor.py:161} INFO - Started process (PID=8480) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:24:17.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:24:17.748+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:17.747+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:24:17.792+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:17.791+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:24:17.809+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:17.808+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:24:17.810+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:17.810+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:24:17.815+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:17.815+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:24:17.815+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:17.815+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:24:17.815+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:17.815+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:24:17.836+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:24:17.850+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:17.850+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:24:17.863+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:17.863+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:24:17.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.158 seconds
[2025-08-07T00:24:48.351+0000] {processor.py:161} INFO - Started process (PID=8495) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:24:48.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:24:48.361+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:48.361+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:24:48.403+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:48.402+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:24:48.430+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:48.429+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:24:48.432+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:48.432+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:24:48.437+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:48.437+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:24:48.437+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:48.437+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:24:48.437+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:48.437+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:24:48.457+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:24:48.471+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:48.471+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:24:48.481+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:24:48.481+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:24:48.493+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.154 seconds
[2025-08-07T00:25:18.971+0000] {processor.py:161} INFO - Started process (PID=8510) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:25:18.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:25:18.982+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:18.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:25:19.014+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:19.014+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:25:19.030+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:19.030+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:25:19.031+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:19.031+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:25:19.035+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:19.035+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:25:19.036+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:19.036+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:25:19.036+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:19.036+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:25:19.055+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:25:19.065+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:19.065+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:25:19.074+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:19.074+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:25:19.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.128 seconds
[2025-08-07T00:25:49.574+0000] {processor.py:161} INFO - Started process (PID=8545) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:25:49.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:25:49.583+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:49.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:25:49.615+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:49.615+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:25:49.636+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:49.636+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:25:49.637+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:49.637+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:25:49.641+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:49.641+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:25:49.641+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:49.641+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:25:49.641+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:49.641+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:25:49.660+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:25:49.759+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:49.759+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:25:49.769+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:25:49.769+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:25:49.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.219 seconds
[2025-08-07T00:26:20.295+0000] {processor.py:161} INFO - Started process (PID=8560) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:26:20.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:26:20.303+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:20.303+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:26:20.352+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:20.352+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:26:20.394+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:20.394+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:26:20.397+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:20.397+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:26:20.401+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:20.401+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:26:20.402+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:20.402+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:26:20.402+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:20.402+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:26:20.428+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:26:20.458+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:20.458+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:26:20.470+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:20.470+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:26:20.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.204 seconds
[2025-08-07T00:26:51.000+0000] {processor.py:161} INFO - Started process (PID=8575) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:26:51.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:26:51.011+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:51.011+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:26:51.056+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:51.056+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:26:51.081+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:51.081+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:26:51.084+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:51.083+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:26:51.090+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:51.090+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:26:51.090+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:51.090+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:26:51.091+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:51.091+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:26:51.132+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:26:51.144+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:51.144+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:26:51.158+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:26:51.158+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:26:51.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.193 seconds
[2025-08-07T00:27:21.642+0000] {processor.py:161} INFO - Started process (PID=8590) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:27:21.644+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:27:21.651+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:21.651+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:27:21.682+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:21.682+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:27:21.698+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:21.698+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:27:21.700+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:21.700+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:27:21.704+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:21.704+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:27:21.704+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:21.704+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:27:21.704+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:21.704+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:27:21.728+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:27:21.741+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:21.741+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:27:21.752+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:21.752+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:27:21.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.135 seconds
[2025-08-07T00:27:52.279+0000] {processor.py:161} INFO - Started process (PID=8605) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:27:52.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:27:52.286+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:52.286+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:27:52.314+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:52.314+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:27:52.331+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:52.331+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:27:52.333+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:52.333+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:27:52.337+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:52.337+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:27:52.337+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:52.337+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:27:52.338+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:52.338+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:27:52.354+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:27:52.365+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:52.365+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:27:52.376+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:27:52.375+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:27:52.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.116 seconds
[2025-08-07T00:28:22.827+0000] {processor.py:161} INFO - Started process (PID=8620) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:28:22.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:28:22.832+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:22.832+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:28:22.861+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:22.861+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:28:22.874+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:22.874+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:28:22.876+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:22.876+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:28:22.879+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:22.879+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:28:22.880+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:22.879+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:28:22.880+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:22.880+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:28:22.898+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:28:22.908+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:22.908+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:28:22.921+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:22.921+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:28:22.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.117 seconds
[2025-08-07T00:28:53.444+0000] {processor.py:161} INFO - Started process (PID=8635) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:28:53.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:28:53.452+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:53.451+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:28:53.494+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:53.494+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:28:53.515+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:53.515+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:28:53.516+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:53.516+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:28:53.522+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:53.522+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:28:53.522+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:53.522+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:28:53.522+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:53.522+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:28:53.542+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:28:53.554+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:53.554+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:28:53.565+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:28:53.565+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:28:53.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.154 seconds
[2025-08-07T00:29:24.123+0000] {processor.py:161} INFO - Started process (PID=8650) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:29:24.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:29:24.129+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:24.128+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:29:24.162+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:24.162+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:29:24.180+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:24.180+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:29:24.182+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:24.182+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:29:24.186+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:24.186+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:29:24.186+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:24.186+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:29:24.186+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:24.186+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:29:24.206+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:29:24.216+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:24.216+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:29:24.227+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:24.226+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:29:24.236+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.127 seconds
[2025-08-07T00:29:54.715+0000] {processor.py:161} INFO - Started process (PID=8665) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:29:54.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:29:54.726+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:54.725+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:29:54.769+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:54.769+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:29:54.789+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:54.789+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:29:54.790+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:54.790+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:29:54.794+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:54.794+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:29:54.794+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:54.794+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:29:54.794+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:54.794+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:29:54.818+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:29:54.831+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:54.831+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:29:54.839+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:29:54.839+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:29:54.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.146 seconds
[2025-08-07T00:30:25.393+0000] {processor.py:161} INFO - Started process (PID=8680) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:30:25.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:30:25.400+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:25.399+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:30:25.442+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:25.442+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:30:25.467+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:25.467+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:30:25.470+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:25.470+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:30:25.475+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:25.475+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:30:25.476+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:25.476+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:30:25.476+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:25.476+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:30:25.523+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:30:25.544+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:25.544+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:30:25.555+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:25.555+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:30:25.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.189 seconds
[2025-08-07T00:30:55.975+0000] {processor.py:161} INFO - Started process (PID=8695) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:30:55.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:30:55.980+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:55.979+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:30:56.000+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:56.000+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:30:56.012+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:56.012+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:30:56.013+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:56.013+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:30:56.016+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:56.016+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:30:56.017+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:56.017+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:30:56.017+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:56.017+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:30:56.030+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:30:56.038+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:56.038+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:30:56.046+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:30:56.046+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:30:56.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.091 seconds
[2025-08-07T00:31:26.455+0000] {processor.py:161} INFO - Started process (PID=8710) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:31:26.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:31:26.462+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:26.461+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:31:26.494+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:26.494+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:31:26.506+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:26.506+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:31:26.508+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:26.508+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:31:26.512+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:26.512+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:31:26.513+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:26.513+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:31:26.514+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:26.513+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:31:26.530+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:31:26.542+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:26.541+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:31:26.553+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:26.553+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:31:26.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.120 seconds
[2025-08-07T00:31:57.025+0000] {processor.py:161} INFO - Started process (PID=8725) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:31:57.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:31:57.034+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:57.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:31:57.062+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:57.062+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:31:57.077+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:57.077+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:31:57.079+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:57.078+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:31:57.084+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:57.084+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:31:57.085+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:57.085+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:31:57.085+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:57.085+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:31:57.101+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:31:57.112+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:57.112+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:31:57.125+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:31:57.125+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:31:57.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.121 seconds
[2025-08-07T00:32:27.577+0000] {processor.py:161} INFO - Started process (PID=8740) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:32:27.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:32:27.582+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:27.582+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:32:27.609+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:27.609+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:32:27.620+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:27.620+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:32:27.621+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:27.621+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:32:27.624+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:27.624+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:32:27.624+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:27.624+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:32:27.624+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:27.624+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:32:27.637+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:32:27.645+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:27.645+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:32:27.654+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:27.654+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:32:27.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.096 seconds
[2025-08-07T00:32:58.013+0000] {processor.py:161} INFO - Started process (PID=8755) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:32:58.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:32:58.020+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:58.020+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:32:58.060+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:58.060+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:32:58.080+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:58.080+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:32:58.081+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:58.081+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:32:58.086+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:58.086+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:32:58.087+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:58.087+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:32:58.087+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:58.087+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:32:58.108+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:32:58.121+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:58.121+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:32:58.130+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:32:58.130+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:32:58.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.139 seconds
[2025-08-07T00:33:28.600+0000] {processor.py:161} INFO - Started process (PID=8770) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:33:28.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:33:28.610+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:28.609+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:33:28.645+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:28.644+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:33:28.662+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:28.662+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:33:28.664+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:28.664+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:33:28.668+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:28.668+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:33:28.668+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:28.668+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:33:28.668+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:28.668+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:33:28.686+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:33:28.699+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:28.699+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:33:28.708+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:28.708+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:33:28.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.129 seconds
[2025-08-07T00:33:59.180+0000] {processor.py:161} INFO - Started process (PID=8785) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:33:59.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:33:59.188+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:59.187+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:33:59.223+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:59.223+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:33:59.240+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:59.240+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:33:59.242+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:59.241+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:33:59.245+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:59.245+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:33:59.246+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:59.246+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:33:59.246+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:59.246+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:33:59.263+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:33:59.275+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:59.275+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:33:59.284+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:33:59.283+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:33:59.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.126 seconds
[2025-08-07T00:34:29.684+0000] {processor.py:161} INFO - Started process (PID=8800) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:34:29.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:34:29.693+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:34:29.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:34:29.723+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:34:29.723+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:34:29.733+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:34:29.733+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:34:29.734+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:34:29.734+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:34:29.738+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:34:29.738+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:34:29.739+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:34:29.739+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:34:29.739+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:34:29.739+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:34:29.759+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:34:29.769+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:34:29.769+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:34:29.778+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:34:29.778+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:34:29.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.115 seconds
[2025-08-07T00:35:00.194+0000] {processor.py:161} INFO - Started process (PID=8815) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:35:00.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:35:00.203+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:00.202+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:35:00.237+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:00.237+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:35:00.249+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:00.249+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:35:00.250+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:00.250+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:35:00.254+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:00.254+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:35:00.254+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:00.254+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:35:00.254+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:00.254+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:35:00.275+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:35:00.286+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:00.286+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:35:00.297+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:00.297+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:35:00.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.121 seconds
[2025-08-07T00:35:30.737+0000] {processor.py:161} INFO - Started process (PID=8830) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:35:30.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:35:30.743+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:30.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:35:30.778+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:30.778+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:35:30.793+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:30.793+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:35:30.796+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:30.796+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:35:30.799+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:30.799+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:35:30.800+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:30.800+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:35:30.800+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:30.800+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:35:30.819+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:35:30.831+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:30.831+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:35:30.842+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:35:30.842+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:35:30.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.129 seconds
[2025-08-07T00:36:01.314+0000] {processor.py:161} INFO - Started process (PID=8845) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:36:01.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:36:01.320+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:01.319+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:36:01.351+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:01.351+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:36:01.366+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:01.366+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:36:01.367+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:01.367+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:36:01.372+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:01.372+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:36:01.373+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:01.373+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:36:01.373+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:01.373+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:36:01.391+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:36:01.402+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:01.402+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:36:01.412+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:01.412+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:36:01.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.116 seconds
[2025-08-07T00:36:31.897+0000] {processor.py:161} INFO - Started process (PID=8860) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:36:31.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:36:31.903+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:31.902+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:36:31.936+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:31.936+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:36:31.950+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:31.950+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:36:31.952+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:31.952+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:36:31.956+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:31.956+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:36:31.956+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:31.956+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:36:31.956+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:31.956+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:36:31.977+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:36:31.989+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:31.989+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:36:31.998+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:36:31.998+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:36:32.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.125 seconds
[2025-08-07T00:37:02.506+0000] {processor.py:161} INFO - Started process (PID=8875) to work on /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:37:02.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load/s3_to_snowflake_loader.py for tasks to queue
[2025-08-07T00:37:02.513+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:37:02.512+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:37:02.542+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:37:02.542+0000] {base.py:84} INFO - Using connection ID 'mysql_local' for task execution.
[2025-08-07T00:37:02.559+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:37:02.559+0000] {sql.py:470} INFO - Running statement: SELECT table_name, s3_path FROM etl_table_config WHERE is_active = TRUE, parameters: None
[2025-08-07T00:37:02.561+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:37:02.561+0000] {sql.py:479} INFO - Rows affected: 5
[2025-08-07T00:37:02.564+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:37:02.564+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-07T00:37:02.565+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:37:02.565+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-07T00:37:02.565+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:37:02.565+0000] {connection_wrapper.py:401} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') session token retrieved from extra, please note you are responsible for renewing these.
[2025-08-07T00:37:02.587+0000] {processor.py:840} INFO - DAG(s) 's3_to_snowflake_loader' retrieved from /opt/airflow/dags/load/s3_to_snowflake_loader.py
[2025-08-07T00:37:02.597+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:37:02.597+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-08-07T00:37:02.606+0000] {logging_mixin.py:188} INFO - [2025-08-07T00:37:02.606+0000] {dag.py:3954} INFO - Setting next_dagrun for s3_to_snowflake_loader to None, run_after=None
[2025-08-07T00:37:02.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load/s3_to_snowflake_loader.py took 0.123 seconds
